POST http://localhost:8080/ca2/api/login
Content-Type: application/json

{
  "username": "user",
  "password": "As123456"
}
###
GET http://localhost:8080/ca2/api/info/admin
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjY4MjQ2NzAyLCJpYXQiOjE2NjgyNDQ5MDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.s0EV1iC3EjNJ3eVk7nyb8UAIQHB08F5YDsGmgw8JxZE

### query is a string caontaining either the id of a pokémon or it's name
POST http://localhost:8080/ca2/api/info/pokemon
Content-Type: application/json

{
  "query": "133"
}

### deckSize is clamped in frontend to be be a whole number from 1 to 10 inclusive
POST http://localhost:8080/ca2/api/info/pokemondeck
Content-Type: application/json

{
"deckSize": "10"
}

### getMultiAnime
POST http://localhost:8080/ca2/api/info/anime/multi
Content-Type: application/json
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjY4MjQ2NzAyLCJpYXQiOjE2NjgyNDQ5MDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.s0EV1iC3EjNJ3eVk7nyb8UAIQHB08F5YDsGmgw8JxZE

{
  "query": "Cowboy Bebop"
}

### getSingleAnime
POST http://localhost:8080/ca2/api/info/anime/single
Content-Type: application/json
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjY4MjQ2NzAyLCJpYXQiOjE2NjgyNDQ5MDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.s0EV1iC3EjNJ3eVk7nyb8UAIQHB08F5YDsGmgw8JxZE

{
  "query": "Cowboy Bebop"
}

### addAnimeToList
POST http://localhost:8080/ca2/api/info/user/watchlist/add
Content-Type: application/json
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjY4MjQ2NzAyLCJpYXQiOjE2NjgyNDQ5MDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.s0EV1iC3EjNJ3eVk7nyb8UAIQHB08F5YDsGmgw8JxZE

{
  "username": "user",
  "anime": {
    "id": 162,
    "name": "Initial D First Stage",
    "year": "1998",
    "status": "finished",
    "posterURL": "https://media.kitsu.io/anime/poster_images/162/original.png"
  }
}

### removeAnimeFromList
POST http://localhost:8080/ca2/api/info/user/watchlist/remove
Content-Type: application/json
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOiJ1c2VyIiwiZXhwIjoxNjY4MjQ2NzAyLCJpYXQiOjE2NjgyNDQ5MDIsImlzc3VlciI6InNlbWVzdGVyc3RhcnRjb2RlLWRhdDMiLCJ1c2VybmFtZSI6InVzZXIifQ.s0EV1iC3EjNJ3eVk7nyb8UAIQHB08F5YDsGmgw8JxZE

{
  "username": "user",
  "animeId": 162
}